addressbook/addressbook/urls.py
"""Primary URL's routing file."""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import static as static_views
from contacts import views as contact_views


urlpatterns = [
    url(r'^$', contact_views.index, name='index'),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(.*)$', static_views.serve,
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
        url(r'^media/(.*)$', static_views.serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ]

addressbook/avatar/urls.py
from django.conf.urls import url

from avatar import views

app_name = 'avatar'

urlpatterns = [
    url(r'^add/$', views.add, name='avatar_add'),
    url(r'^render_primary/(?P<contact>[\w\d\@\.\-_]{3,30})/(?P<size>[\d]+)/$',
        views.render_primary, name='avatar_render_primary'),
    url(r'^list/(?P<codename>[\+\w\@\.]+)/(?P<id>[\d]+)/$', views.avatar, name='avatar'),
]

addressbook/contacts/urls.py
"""URL's routing file for all contact urls except 'index' URL."""

from django.conf.urls import url

from contacts import views

app_name = 'contacts'

urlpatterns = [
    url(r'^create/details/$', views.create_details, name='create_contact_details'),
    url(r'^update/details/(?P<contact_id>\d{1,10})/$', views.update_details,
        name='update_contact_details'),
    url(r'^update/avatar/(?P<contact_id>\d{1,10})/$', views.update_avatar,
        name='update_contact_avatar'),
    url(r'^update/powers/(?P<contact_id>\d{1,10})/$', views.update_powers,
        name='update_contact_powers'),
    url(r'^delete/(?P<contact_id>\d{1,10})/$', views.delete, name='delete_contact'),
]

addressbook/contacts/models.py
"""Models required to support all contact details for the address book."""

from __future__ import unicode_literals

from django.db import models

from contacts.lib.contact_grader import Grader


def contact_directory_path(instance, filename):
    """Return the appropriate folder to store an avatar in."""
    # file will be uploaded to MEDIA_ROOT/avatars/contact_<id>/<filename>
    file_extension = filename.split('.')[-1]
    return 'avatars/contact_{0}/{1}.{2}'.format(instance.id, instance.id, file_extension)


class Contact(models.Model):
    """Model class that represents one specific person in the AddressBook."""

    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    nick_name = models.CharField(max_length=40, null=True, blank=True)
    code_name = models.CharField(max_length=40)
    telephone_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=80, null=True, blank=True)

    def __str__(self):
        """Return superhero name."""
        return self.code_name

    @property
    def full_name(self):
        """Return combined first and last name to give full name."""
        if self.nick_name:
            return '{} "{}" {}'.format(self.first_name, self.nick_name, self.last_name).strip()
        else:
            return '{} {}'.format(self.first_name, self.last_name).strip()

    @property
    def powers(self):
        """Return comma-concatenated list of associated powers."""
        return [p.super_power.power.title() for p in self.super_powers.all()]

    @property
    def avatar(self):
        """Return the primary avatar for the contact (if possible)."""
        if self.avatars.filter(primary=True):
            return self.avatars.filter(primary=True)[0]

        return None

    @property
    def grade(self):
        """Return the power grading of the contact."""
        return Grader(self).grade()


class SuperPower(models.Model):
    """Model class that stores possible super-powers."""

    power = models.CharField(max_length=100)

    def __str__(self):
        """Return name of power."""
        return self.power


class ContactSuperPowers(models.Model):
    """Model class that links contacts to specific super-powers."""

    contact = models.ForeignKey(Contact, related_name='super_powers')
    super_power = models.ForeignKey(SuperPower)

addressbook/contacts/forms.py
from django import forms

from contacts.models import Contact
from avatar.models import Avatar


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'First Name'}),
        error_messages={'required': 'Required'})
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Last Name'}),
        error_messages={'required': 'Required'})

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'nick_name', 'code_name', 'telephone_number', 'email')

addressbook/contacts/views.py
"""Views for processing all Contact requests."""

from django.shortcuts import render, redirect

from contacts.models import Contact
from contacts.forms import ContactForm

from avatar.forms import UploadAvatarForm


def index(request, template_name='contacts/index.html'):
    """View to list all contacts."""
    contacts = Contact.objects.all()
    return render(request, template_name, {'contacts': contacts})


def create_details(request, template_name='contacts/edit_details.html'):
    """View to create a contact by filling in the contact details only."""
    return add_or_update_contact_details(request, template_name, None, "create")


def update_details(request, contact_id, template_name='contacts/edit_details.html'):
    """View to update a contact."""
    contact = Contact.objects.get(id=contact_id)
    return add_or_update_contact_details(request, template_name, contact, "update")


def add_or_update_contact_details(request, template_name, contact, context):
    """
    Either create a new contact or update an existing contacts details.

    request:       the request object passed to the view
    template_name: template to be rendered by this function
    contact:       instance of contact to whom the avatar will be linked - it must exist, even for
                   new contacts
    context:       "create" or "update" depending on how the "template_name" is going to be rendered
    """
    contact_form = ContactForm(request.POST or None, instance=contact)

    if contact_form.is_valid():
        contact = contact_form.save()
        return redirect('contacts:update_contact_avatar', contact_id=contact.id)

    return render(request, template_name, {
        'action': context,
        'contact_form': contact_form
    })


def update_avatar(request, contact_id, template_name='contacts/edit_avatar.html'):
    """View to add a new avatar for a contact."""
    contact = Contact.objects.get(id=contact_id)
    avatar_form = UploadAvatarForm(request.POST or None, request.FILES or None)

    if avatar_form.is_valid():
        avatar_form.save(contact)
        return redirect('contacts:update_contact_powers', contact_id=contact.id)

    return render(request, template_name, {
        'avatar_form': avatar_form,
        'contact': contact
    })


def update_powers(request, contact_id, template_name='contacts/edit_powers.html'):
    """View to update a contact's super-powers."""
    contact = Contact.objects.get(id=contact_id)

    return render(request, template_name, {
        'contact': contact
    })


def delete(request, contact_id):
    """View to delete a contact."""
    Contact.objects.filter(id=contact_id).delete()
    return redirect('index')

addressbook/contacts/templates/contacts/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Python Testing</title>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css" type="text/css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/styles.css" type="text/css">

        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="wrapper">
                <div class="title">My Contacts</div>
                {% block extra_header %}{% endblock %}
            </div>
        </header>

        <div class="wrapper">
            {% block content %}{% endblock %}
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>

        {% block extra_body %}{% endblock %}
    </body>
</html>

addressbook/contacts/templates/contacts/edit_avatar.html
{% extends 'contacts/base.html' %}

{% load avatar_tags %}

{% block content %}
    <h1>Contact Avatar</h1>

    <div id="breadcrumbs">
        <ul>
            <li><a href="{% url 'index' %}">All Contacts</a></li>
            <li>&gt; Avatar</li>
        </ul>
    </div>

    <h2>{{ contact.full_name }}</h2>
    <span>Current Avatar:</span>
    {% if contact.avatar %}
        <br><br>
        {% avatar contact 200 %}
    {% else %}
        <span>None</span>
    {% endif %}
    <br><br>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
            <li>
                <label>Upload new avatar</label>
                <span>{{ avatar_form.avatar }}</span>

                {% if avatar_form.avatar.errors %}
                    {{ avatar_form.avatar.errors }}
                {% endif %}
            </li>
        </ul>

        <input type="submit" value="Next" class="primary_btn" />
        <a class="skip_link" href="{% url 'contacts:update_contact_powers' contact.id %}">Skip</a>
        <a class="back_link" href="{% url 'contacts:update_contact_details' contact.id %}">Back</a>
    </form>
{% endblock content %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/contacts.js" type="text/javascript"></script>
{% endblock %}

addressbook/contacts/templates/contacts/edit_details.html
{% extends 'contacts/base.html' %}

{% block content %}
    <h1>Contact Details</h1>

    <div id="breadcrumbs">
        <ul>
            <li><a href="{% url 'index' %}">All Contacts</a></li>
            <li>&gt; {{ action|title }} Contact</li>
        </ul>
    </div>

    <form action="" method="post">
        {% csrf_token %}
        <ul>
            <li>
                <label>Name</label>
                <span>{{ contact_form.first_name }}&nbsp;&nbsp;{{ contact_form.last_name }}</span>

                {% if contact_form.first_name.errors or contact_form.last_name.errors %}
                    {{ contact_form.first_name.errors }}
                    {{ contact_form.last_name.errors }}
                {% endif %}
            </li>

            <li>
                <label>Nick Name</label>
                <span>{{ contact_form.nick_name }}</span>

                {% if contact_form.nick_name.errors %}
                    {{ contact_form.nick_name.errors }}
                {% endif %}
            </li>

            <li>
                <label>Code Name</label>
                <span>{{ contact_form.code_name }}</span>

                {% if contact_form.code_name.errors %}
                    {{ contact_form.code_name.errors }}
                {% endif %}
            </li>

            <li>
                <label>Telephone Number</label>
                <span>{{ contact_form.telephone_number }}</span>

                {% if contact_form.telephone_number.errors %}
                    {{ contact_form.telephone_number.errors }}
                {% endif %}
            </li>

            <li>
                <label>Email</label>
                <span>{{ contact_form.email }}</span>

                {% if contact_form.email.errors %}
                    {{ contact_form.email.errors }}
                {% endif %}
            </li>
        </ul>

        {{ contact_form.non_field_errors }}
        <input type="submit" value="Next" class="primary_btn" />
    </form>
{% endblock content %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/contacts.js" type="text/javascript"></script>
{% endblock %}

addressbook/contacts/templates/contacts/edit_powers.html
{% extends 'contacts/base.html' %}

{% block content %}
    <h1>Contact Powers</h1>

    <div id="breadcrumbs">
        <ul>
            <li><a href="">All Contacts</a></li>
            <li>&gt; Powers</li>
        </ul>
    </div>

    <h2>{{ contact.full_name }}</h2>
    <span>Known Powers:</span>
    <ul class="powers">
        {% for power in contact.powers %}
            <li>{{ power }}</li>
        {% empty %}
            <li>None</li>
        {% endfor %}
    </ul>
    <a href="#" class="action_update_link">Update Powers from Superhero Bureau</a>

    <br><br>
    <a class="primary_btn" href="{% url 'index' %}">Finish</a>
    <a class="back_link" href="{% url 'contacts:update_contact_avatar' contact.id %}">Back</a>
{% endblock content %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/contacts.js" type="text/javascript"></script>
{% endblock %}

addressbook/contacts/templates/contacts/index.html
{% extends 'contacts/base.html' %}

{% load avatar_tags %}
{% load contacts_tags %}

{% block extra_header %}
    <div class="header_functions">
        <span><a href="{% url 'contacts:create_contact_details' %}">Add Contact</a></span>
    </div>
{% endblock %}

{% block content %}
    <section id="contact_list">
        {% for contact in contacts %}
            <div class="contact highlight_card" data-code_name="{{ contact.code_name }}" data-powers="{{ contact.powers|join:',' }}" data-full_name="{{ contact.full_name }}" data-email="{{ contact.email }}" data-telephone_number="{{ contact.telephone_number }}" data-update_url="{% url 'contacts:update_contact_details' contact.id %}" data-delete_url="{% url 'contacts:delete_contact' contact.id %}" data-grade="{{ contact.grade|grader_reveal }}">
                <div class="header">{{ contact.code_name }}</div>
                {% avatar contact 50 %}
                <div class="detail">{{ contact.first_name }} {{ contact.last_name }}</div>
                <div class="big_avatar hidden">
                    {% avatar contact 200 %}
                </div>
            </div>
        {% endfor %}
    </section>
    <aside id="contact_display" class="hidden" data-active="">
        <div class="title"></div>
        <div class="big_avatar"></div>
        <ul>
            <li class="full_name">
                <span class="heading">Full Name</span>
                <span class="detail"></span>
            </li>
            <li class="powers">
                <span class="heading">Super Powers</span>
                <span class="detail"></span>
            </li>
        </ul>
        <div id="power_grade">
            <div id="power_grade_overlay">&nbsp;</div>
            <div id="power_grade_base">&nbsp;</div>
        </div>
        <br><br>
        <button><a id="contact_update_link" href="">Update</a></button>
        <button><a id="contact_delete_link" href="">Remove</a></button>
        <br><br><br>

        <div class="primary_actions">
            <button class="telephone_number">Call</button>
            <button class="email">Email</button>
        </div>
    </aside>
{% endblock content %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/contacts.js" type="text/javascript"></script>
{% endblock %}